Add implicit so that nvl on a Timestamp followed by >= compiles.
Previously, the compiler would report the following error:
value >= is not a member of org.squeryl.dsl.NvlFunctionNonNumerical[Option[org.squeryl.PrimitiveTypeMode.TimestampType],org.squeryl.PrimitiveTypeMode.TimestampType]